import { RegisterServiceWorker } from '@/components/RegisterServiceWorker';
import { AuthProvider } from '@/context/AuthContext';
import { OnlineProvider } from '@/context/OnlineContext';
import "@/styles/globals.css";
import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Dogão do Pastor - Entregas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning >
      <head>
        <link rel="manifest" href="/manifest.json" />
        <meta name="theme-color" content="#ffffff" />
      </head>
      <body>
        <AuthProvider>
          <OnlineProvider>
            {children}
          </OnlineProvider>
        </AuthProvider>
        <RegisterServiceWorker />
      </body>
    </html >
  );
}
